theme: jekyll-theme-midnight
title: Data Visualization
description: This repository houses assignments done from Karl Ho's Fall 2020 Data Visualization class at the University of Texas at Dallas. We explore a wide variety of topics in data and data science through study and application.
baseurl: /kelu1997
