remote_theme: pages-themes/minimal@v0.2.0
title: Kevin Pennington
description: Currently a ACN graduate student at the University of Texas at Dallas with an interest in machine learning and advanced neural networks.
baseurl: /kelu1997.github.io
show_downloads: False
